<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OmniTrade.Domain\OmniTrade.Domain.csproj" />
    <ProjectReference Include="..\OmniTrade.Brokers.Alpaca\OmniTrade.Brokers.Alpaca.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
